default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>

development:
  channel_prefix: twister_development
  <<: *default

test:
  adapter: test

production:
  channel_prefix: twister_production
  <<: *default