default: &default
  adapter: postgresql
  pool: 20
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  encoding: unicode

development:
  <<: *default
  database: twister_development

test:
  <<: *default
  database: twister_test

production:
  <<: *default
  database: twister_production